apply plugin: 'com.android.library'

group = 'com.primexmeta.aems'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()
useExpoPublishing()

android {
  namespace "com.primexmeta.aems.usage"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}
